# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 293c5bbcd5fb4c8cce9af91e9dd869ea5e3e277bbcc6d0c6b34794df65aa559e5b4aa72ab911e7a1942ed30e0667c0507cae32fbb44095f41ce2aae3cf2f611a

test:
  secret_key_base: f27fae07f80ae0e61eb88f4127fbc8ed6388e7bef75c88fb4687442ad8853505653b71d9748ff6d59a9fbc8d8c98290988200244b83c103a4f2738c0798d427d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
